name: VaderBoard build 

on:
  push:
    branches:
      - main
  pull_request:

    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:

          profile: minimal

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build and test
        run: cargo build --all --verbose && cargo test --all --verbose

